name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Initialize Packages Across Project
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: export PYTHONPATH="${PYTHONPATH}:utk_book_to_manifest/"
      - name: Run Unit Tests
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run python -m unittest --verbose
